export const FUNCTION_PARAM_TYPES = 'design:paramtypes'
export const FUNCTION_RETURN_TYPE = 'design:returntype'
export const PROPERTY_TYPE = 'design:type'
export const PARAMETERS_METADATA = 'graphqlize:params:metadata'
export const TYPE_FIELDS_METADATA = 'graphqlize:fields:metadata'
export const FIELD_RESOLVERS_METADATA = 'graphqlize:field:resolvers:metadata'
export const RESOLVE_TYPE_METADATA = 'graphqlize:resolve:type:metadata'
export const OVERRIDE_NAME_METADATA = 'graphqlize:override:name:metadata'
